name: Deploy Clima API

on:
  push:
    branches: [ main, master ] # Aceita qualquer uma das duas

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Login na Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Configurar Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 'Instalar Dependências'
        run: |
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: 'Deploy para Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'api-clima-mari-projeto'
          package: '.'
  
  build_and_deploy_job:
      runs-on: ubuntu-latest
      name: Build and Deploy Job
      steps:
        - uses: actions/checkout@v3
          with:
            submodules: true

        - name: Build And Deploy
          id: builddeploy
          uses: Azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            action: "upload"
            
            ###### Configurações de Localização ######
            app_location: "/web"          # Onde está o seu projeto React
            api_location: "/api"          # Onde está sua Azure Function
            output_location: "dist"       # Pasta gerada pelo comando 'npm run build' do Vite